/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.Conexion;
import Datos.Vuelos;
import Datos.reservas;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import net.proteanit.sql.DbUtils;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author kevin
 */
public class FRMRESERVAS extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FRMRESERVAS() {
        initComponents();
    }
private void limpiarCampos() {
    TXTRESERVA.setText("");
    TXTVUELO.setText("");
    TXTPASAJERO.setText("");
    TXTPRECIO.setText("Precio");  // Restaurar placeholder
    jDateChooser1.setDate(null);
    cmbEstado.setSelectedIndex(0);
    
    // Enfocar el primer campo para nueva entrada
    TXTRESERVA.requestFocus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        TXTPRECIO = new javax.swing.JLabel();
        lblID2 = new javax.swing.JLabel();
        lblID3 = new javax.swing.JLabel();
        lblID4 = new javax.swing.JLabel();
        TXTPRECIO2 = new javax.swing.JTextField();
        TXTVUELO = new javax.swing.JTextField();
        TXTPASAJERO = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEspecies = new javax.swing.JTable();
        cmbEstado = new javax.swing.JComboBox<>();
        lblID1 = new javax.swing.JLabel();
        TXTRESERVA = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID.setText("Fecha_Reserva");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        TXTPRECIO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TXTPRECIO.setText("Precio");
        getContentPane().add(TXTPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 20));

        lblID2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID2.setText("    ID_Vuelo ");
        getContentPane().add(lblID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblID3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID3.setText(" ID_Pasajero    ");
        getContentPane().add(lblID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 20));

        lblID4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID4.setText(" Estado");
        getContentPane().add(lblID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 20));

        TXTPRECIO2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTPRECIO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPRECIO2ActionPerformed(evt);
            }
        });
        getContentPane().add(TXTPRECIO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 140, 30));

        TXTVUELO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTVUELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTVUELOActionPerformed(evt);
            }
        });
        getContentPane().add(TXTVUELO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, 30));

        TXTPASAJERO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTPASAJERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPASAJEROActionPerformed(evt);
            }
        });
        getContentPane().add(TXTPASAJERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, 30));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        tblEspecies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEspecies);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 710, 290));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confirmada", "Cancelada", " " }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        lblID1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblID1.setText(" ID_Reserva  ");
        getContentPane().add(lblID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TXTRESERVA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTRESERVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRESERVAActionPerformed(evt);
            }
        });
        getContentPane().add(TXTRESERVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, -1));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTPRECIO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPRECIO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPRECIO2ActionPerformed

    private void TXTVUELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTVUELOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTVUELOActionPerformed

    private void TXTPASAJEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPASAJEROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPASAJEROActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
   
        try {
            // TODO add your handling code here:
            //sirve para guardar y modificar
            reservas mireserva = new reservas();
            mireserva.setID_Reserva(Integer.parseInt(TXTRESERVA.getText()));
            mireserva.setID_Vuelo(Integer.parseInt(TXTVUELO.getText()));
            mireserva.setID_Pasajero(Integer.parseInt(TXTPASAJERO.getText()));
            mireserva.setPrecio(Integer.parseInt(TXTPRECIO.getText()));
            mireserva.setEstado(cmbEstado.getSelectedIndex());
            mireserva.setFecha_Reserva(jDateChooser1.getDate());
            
            int indice = 0;
            //actualizar
            
            reservas Consultada = Conexion.obtenerReserva(TXTRESERVA.getText());
            if (Consultada != null){
                indice = Consultada.getID_Reserva();
            }
            else {
                indice = 0;
            }
            
            //actualizar↑
            
            //indice = buscarIndice();
            //Agregar a la lista correspondiente
            if (indice == 0)
            {
                try {
                    //servicio.agregarEspecie(miEspecie);
                    if(Conexion.insertReserva(mireserva)!=0)
                        JOptionPane.showMessageDialog(null, "ESPECIE GUARDADA");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
            }else
            {
                //Actualizar
                //servicio.modificarEspecie(indice, miEspecie);
                try {
                    //servicio.agregarEspecie(miEspecie);
                    if(Conexion.updateReserva(mireserva)!=0)
                        JOptionPane.showMessageDialog(null, "ESPECIE MODIFICADA");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FRMRESERVAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            // TODO add your handling code here:
            //--nuevo modelo para mostrar en la lista
            DefaultListModel miModelo = new DefaultListModel();
            //recorrer la lista de las especies para llenar el modelo y mostrarlo
            /*int id = 0;
            String nombre = "";
            for(int i = 0; i < servicio.obtenerEspecie().size(); i++)
            {
            id = servicio.obtenerEspecie().get(i).getId();
            nombre = servicio.obtenerEspecie().get(i).getNombre();
            
            miModelo.add(i, id + " " + nombre);
            }
            lstEspecies.setModel(miModelo);*/
            
            ResultSet Resultado = null;
            Resultado = Conexion.listarReservas();
            tblEspecies.setModel( DbUtils.resultSetToTableModel(Resultado));
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FRMRESERVAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void TXTRESERVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRESERVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRESERVAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMRESERVAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMRESERVAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMRESERVAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMRESERVAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMRESERVAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTPASAJERO;
    private javax.swing.JLabel TXTPRECIO;
    private javax.swing.JTextField TXTPRECIO2;
    private javax.swing.JTextField TXTRESERVA;
    private javax.swing.JTextField TXTVUELO;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblID3;
    private javax.swing.JLabel lblID4;
    private javax.swing.JTable tblEspecies;
    // End of variables declaration//GEN-END:variables
}
